### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by annielcook** [ydntech/YDNRedesign#22] opened 2015-06-21 19:51 UTC
@floodfish I am working on adding the images and had a few questions

Image aspect ratios needed: 1x1, 2x1, hero for article?

1. Wordpress has the thumbnail size - 150 x 150, do you think it would make sense to modify these dimensions in settings so that the the thumbnail is the size of our 1x1 card - 211 x 211?

2. On our article pages, the hero image doesnt have a fixed aspect ratio and 2x1 would not look good. Should we make a third aspect ratio for this and then should I modify the code so that the aspect ratio is responsive?

**Comment by floodfish** [comment] 2015-06-22 15:20
I think this is a a duplicate of issue #16 

But as to the specific questions:

1. There's no reason to use 150x150. We'll also need to account for retina resolution, so probably at least 422x422  

2. As I recall (which may be totally wrong!), we did want to try the article hero as fixed 2:1. But if not:
2a. If the hero doesn't have a fixed ratio, what's our cropping logic?
2b. Why do you say 2x1 wouldn't look good? Did you try it and it's ugly?

**Comment by annielcook** [comment] 2015-06-23 15:23
@floodfish because the hero image is so wide, 2x1 results in a very tall image that combined with the nav bar pushes all text beneath the initial fold of the page. I used 2x1 for the kahuna and it looks great.

**Comment by floodfish** [comment] 2015-06-23 16:26
OK. We need a design decision about the correct size for the article hero images.

**Closed** 2015-07-01 00:40 UTC
